repos:
  - repo: https://github.com/awebdeveloper/pre-commit-stylelint
    rev: 0.0.2
    hooks:
      - id: stylelint
        additional_dependencies:
          [
            'stylelint@13.13.1',
            'stylelint-config-prettier@8.0.2',
            'stylelint-config-standard@22.0.0',
          ]
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.4.1
    hooks:
      - id: prettier
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.0.0-rc.0
    hooks:
      - id: eslint
